version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/app/entrypoint.sh
    container_name: golang-microservice-database-management-app
    environment:
      - PROFILE=$PROFILE
    networks:
      - golang-microservice-database-management-network
    volumes:
      - .:/go/app
    depends_on:
      - database
      - pgadmin

  db:
    image: postgres:14.3-alpine
    container_name: golang-microservice-database-management-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - golang-microservice-database-management-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: golang-microservice-database-management-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    networks:
      - golang-microservice-database-management-network

networks:
  golang-microservice-database-management-network:
    driver: bridge